[package]
name = "kuzu-httpfs"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
kuzu-common = { path = "../kuzu-common" }
kuzu-function = { path = "../kuzu-function" }
kuzu-catalog = { path = "../kuzu-catalog" }
kuzu-extension = { path = "../kuzu-extension" }
ureq = "3.3"
tempfile = "3.10"
tracing.workspace = true

[lints]
workspace = true
