[package]
name = "akar-optimizer"
version = "0.1.4"
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = true
description = "Query optimizer for the Akar embedded graph database"
keywords.workspace = true
categories.workspace = true
authors.workspace = true

[dependencies]
akar-common = { path = "../akar-common", version = "0.1.0" }
akar-planner = { path = "../akar-planner", version = "0.1.0" }
akar-storage = { path = "../akar-storage", version = "0.1.0" }
akar-binder = { path = "../akar-binder", version = "0.1.0" }
akar-parser = { path = "../akar-parser", version = "0.1.0" }
tracing.workspace = true

[dev-dependencies]
akar-parser = { path = "../akar-parser", version = "0.1.0" }

[lints]
workspace = true
