from typing import Any

class Database:
    def __init__(self, path: str = ..., **kwargs: Any) -> None: ...
    def __del__(self) -> None: ...

class Connection:
    def __init__(self, database: Any) -> None: ...
    def execute(self, query: str, params: Any = ...) -> Any: ...
    def get_ro_connection(self) -> Connection: ...
    def set_max_threads(self, threads: int) -> None: ...
    def set_logger(self, logger: Any) -> None: ...
    def interrupt(self) -> None: ...
    def close(self) -> None: ...
    def __del__(self) -> None: ...

class QueryResult:
    def get_as_df(self) -> Any: ...
    def get_next(self) -> Any: ...
    def has_next(self) -> bool: ...
    def get_column_names(self) -> list[str]: ...
    def get_as_dict(self) -> list[dict[str, Any]]: ...

class NodeVal:
    def get_id(self) -> int: ...
    def get_label(self) -> str: ...
    def get_property(self, name: str) -> Any: ...

class RelVal:
    def get_src_id(self) -> int: ...
    def get_dst_id(self) -> int: ...
    def get_property(self, name: str) -> Any: ...

class KNNResult:
    id: int = ...
    distance: float = ...

class DatabaseType:
    INTEGER: int
    STRING: int
    DOUBLE: int
    FLOAT: int
    BOOL: int
    BLOB: int
    DATE: int
    TIMESTAMP: int
    UUID: int
    LIST: int
    MAP: int
    UNION: int
    STRUCT: int
    ARRAY: int
    RECURSIVE_REL: int
    NODE: int
    REL: int

class search:
    @staticmethod
    def rrf_fuse(sets: list[list[tuple[int, float]]], k: int = ..., limit: int = ...) -> list[dict[str, Any]]: ...
    @staticmethod
    def hybrid_search(*args: Any, **kwargs: Any) -> Any: ...
    @staticmethod
    def multi_perspective_recall(*args: Any, **kwargs: Any) -> Any: ...
    @staticmethod
    def weighted_rrf_fuse_py(*args: Any, **kwargs: Any) -> Any: ...

class spread:
    @staticmethod
    def spread_activation(*args: Any, **kwargs: Any) -> Any: ...
    @staticmethod
    def batch_spread(edges: list[tuple[int, int]], num_nodes: int, start_ids: list[int], *, depth: int = ..., decay: float = ..., threshold: float = ..., k_per_seed: int = ...) -> list[dict[str, Any]]: ...

class dream:
    PyDreamConfig: Any
    PyPhaseStats: Any
    PyDreamStats: Any

class knn:
    pass

class louvain:
    pass

class lstm:
    pass
