[package]
name = "kuzu-processor"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
kuzu-common = { path = "../kuzu-common" }
kuzu-catalog = { path = "../kuzu-catalog" }
kuzu-planner = { path = "../kuzu-planner" }
kuzu-optimizer = { path = "../kuzu-optimizer" }
kuzu-function = { path = "../kuzu-function" }
kuzu-storage = { path = "../kuzu-storage" }
kuzu-parser = { path = "../kuzu-parser" }
tracing.workspace = true
thiserror.workspace = true
hashbrown.workspace = true

[dev-dependencies]
kuzu-binder = { path = "../kuzu-binder" }
