[package]
name = "kuzu-delta"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
kuzu-function = { path = "../kuzu-function" }
kuzu-extension = { path = "../kuzu-extension" }
kuzu-duckdb = { path = "../kuzu-duckdb", optional = true }
tracing.workspace = true

[features]
default = []
duckdb-delegation = ["kuzu-duckdb/bundled"]

[lints]
workspace = true
