[package]
name = "akar-extension"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = true
description = "Extension framework for the Akar embedded graph database"
keywords.workspace = true
categories.workspace = true
authors.workspace = true

[features]
default = []
arrow = ["dep:arrow"]

[dependencies]
akar-common = { path = "../akar-common", version = "0.1.0" }
akar-function = { path = "../akar-function", version = "0.1.0" }
akar-catalog = { path = "../akar-catalog", version = "0.1.0" }
tracing.workspace = true
arrow = { workspace = true, optional = true }

[lints]
workspace = true
