[package]
name = "kuzu-algo"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
arrow.workspace = true
kuzu-common = { path = "../kuzu-common" }
kuzu-function = { path = "../kuzu-function" }
kuzu-extension = { path = "../kuzu-extension" }
kuzu-graph = { path = "../kuzu-graph" }
tracing.workspace = true

[dev-dependencies]
kuzu-catalog = { path = "../kuzu-catalog" }

[lints]
workspace = true
