[package]
name = "kuzu-llm"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
kuzu-common = { path = "../kuzu-common" }
kuzu-function = { path = "../kuzu-function" }
kuzu-catalog = { path = "../kuzu-catalog" }
kuzu-extension = { path = "../kuzu-extension" }
serde_json.workspace = true
tracing.workspace = true
ureq.workspace = true
