[package]
name = "akar-dream"
version = "0.1.15"
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = true
description = "Dream engine orchestration for the Akar embedded graph database"
keywords.workspace = true
categories.workspace = true
authors.workspace = true

[dependencies]
akar-algo = { path = "../akar-algo", version = "0.1.6" }

[dev-dependencies]

[lints]
workspace = true
