[package]
name = "akar-neo4j"
version = "0.1.2"
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = true
description = "Neo4j integration for the Akar embedded graph database"
keywords.workspace = true
categories.workspace = true
authors.workspace = true

[dependencies]
akar-function = { path = "../akar-function", version = "0.1.2" }
akar-extension = { path = "../akar-extension", version = "0.1.1" }
tracing.workspace = true

[lints]
workspace = true
