[package]
name = "kuzu"
version = "0.12.0"
description = "An in-process property graph database management system built for query speed and scalability"
keywords = ["database", "graph"]
license = "MIT"
categories = ["database"]

rust-version = "1.81"
edition = "2021"

[dependencies]
kuzu-main = { path = "../../kuzu-core/kuzu-main" }
kuzu-common = { path = "../../kuzu-core/kuzu-common" }

[dev-dependencies]
anyhow = "1"
tempfile = "3"

[package.metadata.docs.rs]
all-features = true

[profile.relwithdebinfo]
inherits = "release"
debug = true

[lints.clippy]
cargo = { level = "warn", priority = -1 }
correctness = { level = "warn", priority = -1 }
perf = { level = "warn", priority = -1 }
style = { level = "warn", priority = -1 }
suspicious = { level = "warn", priority = -1 }

complexity = { level = "warn", priority = -1 }
too_many_arguments = "allow"
type_complexity = "allow"

pedantic = { level = "warn", priority = -1 }
inline_always = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
module_name_repetitions = "allow"
must_use_candidate = "allow"
needless_pass_by_value = "allow"
redundant_closure_for_method_calls = "allow"
return_self_not_must_use = "allow"
similar_names = "allow"
struct_excessive_bools = "allow"
too_many_lines = "allow"
unreadable_literal = "allow"
