[package]
name = "kuzu-binder"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
kuzu-common = { path = "../kuzu-common" }
kuzu-parser = { path = "../kuzu-parser" }
kuzu-catalog = { path = "../kuzu-catalog" }
tracing.workspace = true
thiserror.workspace = true
hashbrown.workspace = true

[lints]
workspace = true
