[package]
name = "akar-binder"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
akar-common = { path = "../akar-common" }
akar-parser = { path = "../akar-parser" }
akar-catalog = { path = "../akar-catalog" }

[lints]
workspace = true
