[package]
name = "akar-binder"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = true
description = "Query binder and semantic analysis for the Akar embedded graph database"
keywords.workspace = true
categories.workspace = true
authors.workspace = true

[dependencies]
akar-common = { path = "../akar-common", version = "0.1.0" }
akar-parser = { path = "../akar-parser", version = "0.1.0" }
akar-catalog = { path = "../akar-catalog", version = "0.1.0" }

[lints]
workspace = true
