[package]
name = "kuzu-azure"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
arrow.workspace = true
kuzu-common = { path = "../kuzu-common" }
kuzu-function = { path = "../kuzu-function" }
kuzu-extension = { path = "../kuzu-extension" }
kuzu-duckdb = { path = "../kuzu-duckdb", optional = true }
ureq = "3.3.0"
tempfile = "3.10"
tracing.workspace = true

[features]
default = []
duckdb-delegation = ["kuzu-duckdb/bundled"]
native = []

[lints]
workspace = true
