[package]
name = "kuzu-sqlite"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
kuzu-function = { path = "../kuzu-function" }
kuzu-extension = { path = "../kuzu-extension" }
rusqlite = { version = "0.40.1", features = ["bundled"], optional = true }
tracing.workspace = true

[features]
default = []
bundled = ["rusqlite/bundled"]

[lints]
workspace = true
