[package]
name = "akar-postgres"
version = "0.1.19"
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = true
description = "PostgreSQL extension for the Akar embedded graph database"
keywords.workspace = true
categories.workspace = true
authors.workspace = true

[dependencies]
akar-function = { path = "../akar-function", version = "0.1.2" }
akar-extension = { path = "../akar-extension", version = "0.1.1" }
tokio = { version = "1", features = ["rt", "rt-multi-thread"], optional = true }
tokio-postgres = { version = "0.7", features = ["with-chrono-0_4", "with-uuid-1", "with-serde_json-1"], optional = true }
tracing.workspace = true

[features]
default = []
native = ["tokio", "tokio-postgres"]

[dev-dependencies]
akar-catalog = { path = "../akar-catalog", version = "0.1.1" }
akar-common = { path = "../akar-common", version = "0.1.3" }
akar-extension = { path = "../akar-extension", version = "0.1.1" }
[lints]
workspace = true
