[package]
name = "akar-catalog"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = true
description = "Catalog and metadata management for the Akar embedded graph database"
keywords.workspace = true
categories.workspace = true
authors.workspace = true

[dependencies]
akar-common = { path = "../akar-common", version = "0.1.0" }
hashbrown.workspace = true
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true
