[package]
name = "akar-httpfs"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false
description = "HTTP filesystem extension for the Akar embedded graph database"
keywords.workspace = true
categories.workspace = true
authors.workspace = true

[dependencies]
arrow.workspace = true
akar-common = { path = "../akar-common" }
akar-function = { path = "../akar-function" }
akar-extension = { path = "../akar-extension" }
ureq = "3.3.0"
tempfile = "3.10"
tracing.workspace = true

[lints]
workspace = true
