[package]
name = "kuzu-neo4j"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
kuzu-common = { path = "../kuzu-common" }
kuzu-function = { path = "../kuzu-function" }
kuzu-catalog = { path = "../kuzu-catalog" }
kuzu-extension = { path = "../kuzu-extension" }
tracing.workspace = true
