[package]
name = "kuzu-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
kuzu-main = { path = "../kuzu-main" }
kuzu-common = { path = "../kuzu-common" }
kuzu-parser = { path = "../kuzu-parser" }
kuzu-catalog = { path = "../kuzu-catalog" }
tracing.workspace = true
tracing-subscriber.workspace = true
rustyline = "18"
dirs = "6.0.0"

[lints]
workspace = true
