[package]
name = "kuzu-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
kuzu-main = { path = "../kuzu-main" }
kuzu-common = { path = "../kuzu-common" }
kuzu-parser = { path = "../kuzu-parser" }
tracing.workspace = true
tracing-subscriber.workspace = true
atty = "0.2"
