[package]
name = "kuzu-function"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
kuzu-common = { path = "../kuzu-common" }
arrow.workspace = true
hashbrown.workspace = true
regex.workspace = true
time.workspace = true
md-5.workspace = true
sha2.workspace = true
base64.workspace = true

[lints]
workspace = true
