[package]
name = "kuzu-catalog"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
kuzu-common = { path = "../kuzu-common" }
kuzu-transaction = { path = "../kuzu-transaction" }
tracing.workspace = true
serde.workspace = true
thiserror.workspace = true
hashbrown.workspace = true
