[package]
name = "akar-planner"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = true
description = "Query planner for the Akar embedded graph database"
keywords.workspace = true
categories.workspace = true
authors.workspace = true

[dependencies]
akar-common = { path = "../akar-common" }
akar-binder = { path = "../akar-binder" }
akar-parser = { path = "../akar-parser" }
akar-catalog = { path = "../akar-catalog" }

[dev-dependencies]
akar-parser = { path = "../akar-parser" }
akar-catalog = { path = "../akar-catalog" }

[lints]
workspace = true
