[package]
name = "akar-planner"
version = "0.1.13"
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = true
description = "Query planner for the Akar embedded graph database"
keywords.workspace = true
categories.workspace = true
authors.workspace = true

[dependencies]
akar-common = { path = "../akar-common", version = "0.1.3" }
akar-binder = { path = "../akar-binder", version = "0.1.5" }
akar-parser = { path = "../akar-parser", version = "0.1.2" }
akar-catalog = { path = "../akar-catalog", version = "0.1.1" }

[dev-dependencies]
akar-parser = { path = "../akar-parser", version = "0.1.2" }
akar-catalog = { path = "../akar-catalog", version = "0.1.1" }
[lints]
workspace = true
