[package]
name = "akar-function"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = true
description = "Function registry and expression evaluation for the Akar embedded graph database"
keywords.workspace = true
categories.workspace = true
authors.workspace = true

[dependencies]
akar-common = { path = "../akar-common" }
arrow.workspace = true
hashbrown.workspace = true
regex.workspace = true
time.workspace = true
md-5.workspace = true
sha2.workspace = true
base64.workspace = true

[lints]
workspace = true
