[package]
name = "akar-vector"
version = "0.1.19"
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = true
description = "Vector search extension for the Akar embedded graph database"
keywords.workspace = true
categories.workspace = true
authors.workspace = true

[dependencies]
akar-common = { path = "../akar-common", version = "0.1.3" }
akar-function = { path = "../akar-function", version = "0.1.2" }
akar-extension = { path = "../akar-extension", version = "0.1.1" }
tracing.workspace = true

[lints]
workspace = true
