[package]
name = "akar-parser"
version = "0.1.12"
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = true
description = "Cypher parser for the Akar embedded graph database"
keywords.workspace = true
categories.workspace = true
authors.workspace = true

[dependencies]
pest = "2"
pest_derive = "2"

[dev-dependencies]
pest = "2"

[lints]
workspace = true
